whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/adollshouse.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/adollshouse.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/adventuresinsayingyes.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/adventuresinsayingyes.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/alternateithicatom.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/alternateithicatom.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/auditory_localizer.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/auditory_localizer.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/avatar.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/avatar.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/buck.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/buck.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/exorcism.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/exorcism.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/eyespy.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/eyespy.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/fromboyhoodtofatherhood.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/fromboyhoodtofatherhood.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/hangtime.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/hangtime.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/haveyoumethimyet.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/haveyoumethimyet.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/howtodraw.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/howtodraw.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/inamoment.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/inamoment.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/itsabox.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/itsabox.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/legacy.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/legacy.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/life.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/life.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/myfirstdaywiththeyankees.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/myfirstdaywiththeyankees.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/naked.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/naked.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/odetostepfather.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/odetostepfather.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/sloth.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/sloth.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/souls.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/souls.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/stagefright.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/stagefright.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/swimmingwithastronauts.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/swimmingwithastronauts.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/thatthingonmyarm.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/thatthingonmyarm.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/theclosetthatateeverything.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/theclosetthatateeverything.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/tildeath.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/tildeath.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/undertheinfluence.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/undertheinfluence.wav.txt
whisper /cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/wheretheressmoke.wav --model medium >/cw/liir_data/NoCsBack/cross_modal_brain/story_stimuli/audios/wheretheressmoke.wav.txt
